parameters:
  logger:
    fingers_cross: false
    fingers_cross_log_level: 'debug'

  google:
    credentials_file_path: '%SITEMAPS_INDEXING_GOOGLE_CREDENTIALS%'

  database:
    database: '%SITEMAPS_INDEXING_DB_NAME%'
    user: '%SITEMAPS_INDEXING_DB_USER%'
    password: '%SITEMAPS_INDEXING_DB_PASSWORD%'
    host: '%SITEMAPS_INDEXING_DB_HOST%'
    port: '%SITEMAPS_INDEXING_DB_PORT%'

  authentication:
    secret_key: '%SECRET_KEY%'
